global:
  scrape_interval:     5s # By default, scrape targets every 15 seconds.
  external_labels:
    monitor: 'api-mockup-test-01'

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'msr'
    static_configs:
      - targets: ['msr-test-01:5555']

  - job_name: 'jmeter'
    static_configs:
      - targets: ['jmeter:9270']
