<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">generateRandomStringOfGivenLength</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUNCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vy
c29yKCk7DQpTdHJpbmcgbGVuZ3RoID0gSURhdGFVdGlsLmdldFN0cmluZyhwaXBlbGluZUN1cnNv
ciwgImxlbmd0aCIpOw0KcGlwZWxpbmVDdXJzb3IuZGVzdHJveSgpOw0KDQpMb25nIGwgPSAwbDsN
CmlmIChudWxsID09IGxlbmd0aCB8fCAiIi5lcXVhbHMobGVuZ3RoKSkNCglsZW5ndGggPSAiNTEy
IjsgLy8gZGVmYXVsdCB2YWx1ZQ0KdHJ5ew0KCWwgPSBMb25nLnBhcnNlTG9uZyhsZW5ndGgpOw0K
fWNhdGNoKE51bWJlckZvcm1hdEV4Y2VwdGlvbiBuZmUpew0KCXRocm93IG5ldyBTZXJ2aWNlRXhj
ZXB0aW9uKCJDYW5ub3QgZ2VuZXJhdGUgcmFuZG9tIHN0cmluZyBvZiBub24gbnVtYmVyIGxlbmd0
aDogIiArIGxlbmd0aCk7DQp9DQoNCg0KLy8gY2hvc2UgYSBDaGFyYWN0ZXIgcmFuZG9tIGZyb20g
dGhpcyBTdHJpbmcNClN0cmluZyBBbHBoYU51bWVyaWNTdHJpbmcgPSAiQUJDREVGR0hJSktMTU5P
UFFSU1RVVldYWVoiICsgIjAxMjM0NTY3ODkiICsgImFiY2RlZmdoaWprbG1ub3BxcnN0dXZ4eXoi
Ow0KDQovLyBjcmVhdGUgU3RyaW5nQnVmZmVyIHNpemUgb2YgQWxwaGFOdW1lcmljU3RyaW5nDQpT
dHJpbmdCdWlsZGVyIHNiID0gbmV3IFN0cmluZ0J1aWxkZXIoKTsNCg0KZm9yIChpbnQgaSA9IDA7
IGkgPCBsOyBpKyspIHsNCg0KLy8gZ2VuZXJhdGUgYSByYW5kb20gbnVtYmVyIGJldHdlZW4NCi8v
IDAgdG8gQWxwaGFOdW1lcmljU3RyaW5nIHZhcmlhYmxlIGxlbmd0aA0KCWludCBpbmRleCA9IChp
bnQpIChBbHBoYU51bWVyaWNTdHJpbmcubGVuZ3RoKCkgKiBNYXRoLnJhbmRvbSgpKTsNCg0KCS8v
IGFkZCBDaGFyYWN0ZXIgb25lIGJ5IG9uZSBpbiBlbmQgb2Ygc2INCglzYi5hcHBlbmQoQWxwaGFO
dW1lcmljU3RyaW5nLmNoYXJBdChpbmRleCkpOw0KfQ0KDQovLyBwaXBlbGluZQ0KSURhdGFDdXJz
b3IgcGlwZWxpbmVDdXJzb3JfMSA9IHBpcGVsaW5lLmdldEN1cnNvcigpOw0KSURhdGFVdGlsLnB1
dChwaXBlbGluZUN1cnNvcl8xLCAiZ2VuZXJhdGVkU3RyaW5nIiwgc2IudG9TdHJpbmcoKSk7DQpw
aXBlbGluZUN1cnNvcl8xLmRlc3Ryb3koKTsNCgk=</value>
</Values>
